{"uuid":"4d1db947-0919-49c2-8b93-4df595845c5d","historyId":null,"status":"broken","statusDetails":{"message":"Oops...we found an error preparing this test file:\n\n  > cypress\\e2e\\interceptTest.cy.js\n\n","trace":"\n\nError: Webpack Compilation Error\nModule not found: Error: Can't resolve '../fixtures/data.json' in 'C:\\Users\\conta\\OneDrive\\Documentos\\Reposit√≥rio\\sample-cy-intercept\\cypress\\e2e'\n    at handle (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\@packages\\server\\node_modules\\@cypress\\webpack-preprocessor\\dist\\index.js:212:23)\n    at finalCallback (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:441:32)\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:505:17\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\HookWebpackError.js:68:3\n    at Hook.eval [as callAsync] (eval at create (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\Hook.js:18:14)\n    at Cache.storeBuildDependencies (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Cache.js:122:37)\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:501:19\n    at Hook.eval [as callAsync] (eval at create (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\Hook.js:18:14)\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:498:23\n    at Compiler.emitRecords (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:919:5)\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:490:11\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:885:14\n    at Hook.eval [as callAsync] (eval at create (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\Hook.js:18:14)\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:882:27\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\neo-async\\async.js:2818:7\n    at done (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\neo-async\\async.js:3522:9)\n    at alreadyWritten (C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:714:8)\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:802:19\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\graceful-fs\\graceful-fs.js:123:16\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\@packages\\server\\node_modules\\graceful-fs\\graceful-fs.js:123:16\n    at C:\\Users\\conta\\AppData\\Local\\Cypress\\Cache\\13.6.1\\Cypress\\resources\\app\\node_modules\\@packages\\server\\node_modules\\graceful-fs\\graceful-fs.js:123:16\n    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)\n\nThis occurred while Cypress was compiling and bundling your test code. This is usually caused by:\n\n- A missing file or dependency\n- A syntax error in the file or one of its dependencies\n\nFix the error in your code and re-run your tests."},"stage":"finished","attachments":[],"parameters":[],"labels":[{"name":"suite","value":"interceptTest.cy.js"}],"links":[],"start":null,"name":"Oops...we found an error preparing this test file: interceptTest.cy.js","fullName":"Oops...we found an error preparing this test file: interceptTest.cy.js","stop":null}